### ISSUE TITLE
Change dependencies in setup.py

### ISSUE THREAD

**Issue by smithara** [willjbrown88/geomag_wdc_web_app_interface#8]
https://github.com/willjbrown88/geomag_wdc_web_app_interface/blob/601ce61de225734b326bb2756a660bb9a34fca88/setup.py#L44

Currently:

```
install_requires=["requests==2.12.4",
                      "setuptools==27.2.0",
                      "six==1.10.0",
                      "sphinx==1.5.1"]
```

Fixing the version numbers forces the installation to downgrade currently installed higher versions (potentially breaking other packages). Change them to something like:

```
 install_requires=["requests>=2.12.4, <3.0",
                      "setuptools>=27.2.0",
                      "six>=1.10.0, <2.0",
                      "sphinx>=1.5.1, <2.0"]
```

I think the requirements.txt and `extras_require={"develop"... ` can stay the same for when you really need to ensure an identical environment.

**Comment by willjbrown88** [comment]
Yes, I think you're right here, thanks!

I'll have to make sure this doesn't affect the [MagPySV](https://github.com/gracecox/MagPySV) install (which I think depends on the master branch or PyPI version in difference circumstances).

**Comment by willjbrown88** [comment]
Changes being made in branch:
https://github.com/willjbrown88/geomag_wdc_web_app_interface/tree/dependenciesUpdate

**Comment by willjbrown88** [comment]
MagPySV calls `pip install gmdata_webinterface` in normal use, so PyPI package needs to be rereleased to pick up any changes to the master.

**Comment by willjbrown88** [comment]
There's now a v1.0.8 on PyPI, equivalent to the current master branch and release v1.0.8 on github that fixes this.
